### ISSUE TITLE
False alarm TRIO107 with nested `while`-loops

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/flake8-trio#47]
```python
async def f():
    while True:
        if ...:
            await trio.sleep(0)
            return
        # If you delete this loop, no warning.
        while foo():
            await bar()
```
```
$ flake8 example.py
example.py:1:1: TRIO107: exit from async function with no guaranteed checkpoint
                         or exception since function definition on line 1
```

but plainly deleting the inner loop doesn't change whether the function checkpoints before exiting.

**Comment by jakkdl** [comment]
Something funky going on here about the state not being properly reset after handling a loop, but I think I also never thought of infinite loops with no break (which could also be the issue)
So e.g. this will also raise a false alarm
```python
async def f():
  while True:
    await trio.sleep(0)
    yield
```
since adding the infinite loop functionality that should be an easy check.

But I'm done for the day, will look properly at this tomorrow or so.

**Comment by jakkdl** [comment]
I'm quite confused, I'm not getting different behaviour depending on the presence of that loop or not. But I added logic for infinite loops which I think is the underlying issue.
Nothing popping out to me w/r/t restoring state, so if you find errors with that, or even still reproduce the difference in behavior without merging #52 I'd be interested.

**Comment by Zac-HD** [comment]
I can't repro either, so I guess I just stuffed up somehow when minimizing!

**Comment by jakkdl** [comment]
Ah no worries, but nice that I managed to tease out the actual problem and fix ^^
