### ISSUE TITLE
Handle `functools.partial()` idiom for TRIO113

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/flake8-trio#63]
```python
def __aenter__(self):
    self._nursery.start_soon(trio.run_process, cmd)                       # already emits TRIO113
    self._nursery.start_soon(partial(trio.run_process, cmd, shell=True))  # we want this to emit TRIO113
```

Looking through the code, we actually already handle the `partial()` idiom everywhere else.  It'd be good to add a regression test for `TRIO112` with `partial()` though to make sure that *keeps* working.  (first proposed in https://github.com/Zac-HD/flake8-trio/pull/60#issuecomment-1326281226)

**Comment by jakkdl** [comment]
Did you mean TRIO112 (also) or is that a typo? That doesn't give a crap what context the nursery parameter is put in, and the partial case is covered by e.g.
```python
with trio.open_nursery() as n:
    n.start(foo=tuple(tuple(tuple(tuple(n)))))
```
but I can add one that explicitly uses partial as the function call (instead of tuple) if you want.

TRIO113 could work with the same logic, looking for `trio.run_process` *anywhere* in the first parameter, but I can make it partial-specific to start with.

**Comment by Zac-HD** [comment]
Yep, I did mean TRIO112 in that "this does currently work as desired but I'd like it to be explicitly tested".

And using the same logic of "anywhere in the first parameter" sounds good to me 👍
